module.exports = {
    FUNCTION_CODES: {
        READ_HOLDING_REGISTERS: 3,
        READ_INPUT_REGISTERS: 4,
        WRITE_SINGLE_COIL: 5,
        WRITE_SINGLE_REGISTER: 6,
        START_READ: 8,
        WRITE_MULTIPLE_COILS: 15,
        WRITE_MULTIPLE_REGISTERS: 16,
        READ_ONE_REGISTER: 25,
    },
   DEBUG: true,
    DEFAULT_RETRY_COUNT: 10,
    TASK_RETRY_COUNT: 10,
    RESPONSE_TIMEOUT: 5000,
    QUEUE_TIMEOUT: 150,
    END_PACKET_TIMEOUT: 15
}
